const conversationCorpus = [
  "Assalamu'alaikum, Prof 🙏 Maaf mengganggu waktu istirahatnya.",
  "Wa'alaikumussalam. Ah, silakan masuk. Pikiran yang gelisah memang tak kenal istirahat... Apa yang membawamu kemari? 🤔",
  "(Duduk) Pikiran saya, Prof. Saya baru saja lihat berita terbaru dari G4za... 😥",
  "Ah... P4lest1n4. Luka yang tak kunjung sembuh di jantung umat ini 💔",
  "Saya coba lihat dari sisi sejarah, Prof... lebih dari 75 tahun penindasan, pengusiran, pembantaian. 😔\nTapi rakyat P4lest1n4 itu kok bisa punya energi yang seolah tak pernah padam ya? Dari mana datangnya kekuatan itu? 💪",
  "(Tersenyum tipis) Kamu cari jawabannya di buku, tapi jawaban sesungguhnya tertulis di tanah, udara, dan darah mereka. 🌱\nIni bukan perjuangan 75 tahun. Ini adalah mata rantai dari perjuangan yang jauuuuh lebih panjang.",
  "Maksudnya gimana, Prof? 🤔",
  "Ingat Perang Salib? Berapa lama Salahuddin dan para pendahulunya berjuang membebaskan Al-Quds? ⚔️\nHampir satu abad... generasi lahir dan mati dengan mimpi yang sama.",
  "Oh... jadi ini seperti memori kolektif ya? Gema dari sejarah masa lalu? 😯",
  "Tepat sekali. Bagi rakyat P4lest1n4, tanah itu bukan sekadar geografi. Itu adalah aqidah, warisan para Nabi. 🕌\nDi sana ada jejak Nabi Ibrahim, Daud, Sulaiman, Isa, sampai titik Mi'raj Rasulullah ﷺ.\nBagaimana mungkin mereka menyerahkan tanah yang dijaga oleh ruh para nabi?",
  "Tapi penjajah hari ini, 1sr4el, didukung kekuatan dunia yg luar biasa, Prof. Senjatanya canggih banget. 🛰️\nSementara P4lest1n4... dulu melawan pakai batu pas 1nt1f4d4, sekarang dengan roket rakitan yg jelas tak sebanding. 💥",
  "(Mengambil kitab tua) Coba baca lagi sejarah Perang Badar. 313 melawan seribu. Perlengkapan seadanya melawan kekuatan penuh. ✨\nPembedanya bukan jumlah atau senjata, tapi keyakinan.\nKeyakinan bahwa Allah bersama orang yang sabar dan benar. Itulah senjata terkuat mereka. 🙌",
  "Saya paham soal keyakinan. Tapi kan... secara manusiawi, pasti ada rasa takut juga kan, Prof? 😟",
  "Tentu saja mereka manusia biasa. Mereka merasa takut, sakit, dan berduka. 💔\nTapi ada satu prinsip yg mereka pegang teguh, namanya 'Sumud' (صمود).",
  "Sumud? Apa itu, Prof?",
  "Keteguhan. Ibarat pohon zaitun yang akarnya mencengkeram tanah P4lest1n4 ribuan tahun. 🌳\nDahannya boleh dipatahkan, daunnya boleh gugur, tapi akarnya menolak dicabut.\n'Sumud' itu seni melawan dengan cara 'tetap ada'. Tetap eksis di tanah sendiri, walau tiap hari harus berjuang untuk hidup.",
  "Contohnya seperti petani di Tep1 B4rat yang terus menanam meski diancam pemukim ilegal itu ya?",
  "Betul. Atau seperti ibu-ibu di Sheikh Jarrah yang tetap memasak di depan rumah yg mau digusur. 🥘\nItu bukan putus asa. Itu adalah deklarasi: 'Ini rumahku. Aku tidak akan pergi.' ✊",
  "Luar biasa... tak gentar bahkan saat senjata ada di depan wajah mereka. 😧",
  "Rasa takut mati bisa hilang kalau keyakinan untuk hidup mulia atau mati syahid itu lebih besar. ✨\nMereka sudah lihat ayah, ibu, anak-anak mereka jadi syuhada. Kematian bukan lagi ancaman terbesar.\nAncaman terbesar bagi mereka itu... dilupakan. Dihapus dari sejarah. 🗺️",
  "Makanya mereka terus mewariskan cerita ya? Sampai kunci-kunci rumah tua dari tahun 1948 pun masih disimpan? 🗝️",
  "Tepat sekali! Kunci itu simbol. Simbol hak yg tak akan lekang oleh waktu. ⏳\nMereka bilang ke anak-cucu, 'Ini kunci rumah kita di Jaffa, Haifa, Lod. Suatu hari kita akan kembali.'\nItulah bahan bakar yang menjaga api perjuangan mereka tetap menyala. 🔥",
  "Jadi perlawanannya bukan cuma fisik, tapi juga perlawanan memori. 🧠",
  "Itulah perlawanan yang paling hakiki. Z1on1sme itu dari awal bukan cuma mau merebut tanah, tapi juga merebut narasi/cerita. 📜\nMereka bikin mitos 'tanah tanpa bangsa untuk bangsa tanpa tanah'.\nSetiap puisi, setiap lukisan, setiap lagu perjuangan... itu semua adalah 'peluru' yang menembus kebohongan sejarah itu. 🎯",
  "Mereka menolak jadi sekadar catatan kaki di sejarah orang lain.",
  "Mereka menulis sejarah mereka sendiri. Tintanya adalah darah dan air mata. ✍️",
  "Apa yg bisa kita pelajari dari mereka ya, Prof? Kita yg hidupnya nyaman jauh dari sana...",
  "Pelajaran tentang 'Izzah'. Kehormatan. ✨\nKehormatan itu bukan pada harta atau kuasa, tapi pada sejauh mana kita mempertahankan hak.\nMereka mengajarkan kita, kalah itu bukan saat kita jatuh, tapi saat kita menolak untuk bangkit lagi. 💪",
  "Dan mereka selalu bangkit... setelah Nakba, Perang Enam Hari, Sabra & Shatila, 1nt1f4d4...\n...selalu bangkit lagi. 🤯",
  "Karena mereka sadar, sejarah itu seperti roda. Kadang di atas, kadang di bawah. 🎡\nAndalusia pernah di puncak 800 tahun, lalu runtuh. Konstantinopel tak tertaklukkan 1000 tahun, sampai Al-Fatih datang.\nKeyakinan pada siklus sejarah inilah yang membuat mereka tak pernah putus asa.",
  "Mereka yakin pada janji kemenangan ya?",
  "Mereka percaya janji Allah. Bahwa yg batil akan sirna & yg benar akan datang. ✨\nKapannya itu rahasia Allah. Tugas mereka bukan memastikan KAPAN menang.\nTugas mereka adalah memastikan mereka selalu ada di pihak yg benar SAAT kemenangan itu tiba. 🙏",
  "Pantang menyerah. Tak gentar. 🔥",
  "Betul. Mereka adalah perwujudan nyata dari QS. Ali 'Imran: 139... 'Janganlah kamu bersikap lemah, dan janganlah bersedih hati, padahal kamulah orang-orang yang paling tinggi derajatnya, jika kamu orang-orang yang beriman'. 💪",
  "Ayat itu jadi terasa 'hidup' banget kalau lihat perjuangan mereka.",
  "Sejarah mereka itu seperti tafsir berjalan dari ayat-ayat Qur'an tentang sabar, perjuangan, dan tawakkal.",
  "Kalau media barat bilang mereka teroris...",
  "(Memotong lembut) Tanyakan saja pada sejarah, siapa teroris yg sesungguhnya? 🤔\nYang mempertahankan rumahnya? Atau yg datang dari jauh lalu merampas rumah itu dengan senjata?\nSejarah akan jadi hakim yang adil. Dan sejarah mencatat semuanya. ✍️",
  "Tapi prosesnya terasa lambat dan menyakitkan sekali, Prof. 😔",
  "Emas itu dimurnikan dengan api, bukan dengan belaian. 🔥\nUmat ini sedang 'dimurnikan' di P4lest1n4. Ujian ini melahirkan generasi terbaik.\nBuktinya? Anak-anak kecil di G4za yg hafal Qur'an di tengah reruntuhan.\nMereka itu benih-benih kemenangan di masa depan. 🌱",
  "Bagaimana mereka masih bisa punya harapan ya? 😥",
  "Harapan mereka bukan harapan pasif yg cuma menunggu.\nHarapan mereka adalah TINDAKAN. Setiap shalat di reruntuhan itu harapan. Setiap bayi yg lahir itu harapan. Setiap jengkal tanah yg dipertahankan itu harapan. ✨",
  "Perjuangan mereka ini lebih dari sekadar politik ya, Prof? Ini soal ada atau tiada.",
  "Tepat. Ini pertarungan antara ADA dan TIADA. Antara DIINGAT dan DILUPAKAN.\nDan mereka berjuang gagah berani agar tetap ADA dan selalu DIINGAT. ✊",
  "Jadi teringat kisah Ikrimah bin Abu Jahal. Dulu musuh besar Islam, akhirnya jadi martir heroik.\nDia bertempur sampai titik darah penghabisan sambil bilang, 'Dulu aku melawan Rasulullah, masa hari ini aku lari dari kalian?!' ⚔️",
  "Nah, semangat itu! Semangat penebusan & pembuktian. 🔥\nRakyat P4lest1n4 seolah bilang ke seluruh dunia Islam, 'Kami di garis depan. Kami jaga Al-Aqsa untuk kalian.'\n'Kami tidak akan lari. Kami tidak akan menyerah.' 🇵🇸",
  "Beban yang luar biasa berat... 😔",
  "Tapi Allah tidak akan membebani suatu kaum di luar kesanggupannya.\nDipilihnya mereka justru menunjukkan betapa kuat iman dan jiwa mereka. 💪",
  "Jadi, melihat P4lest1n4 itu bukan untuk bikin kita sedih dan putus asa ya?",
  "Sama sekali bukan. Justru untuk membangkitkan 'ruh jihad' kita dalam arti luas. 🔥\nJihad melawan kebodohan, kemalasan, ketidakpedulian.\nPerjuangan mereka itu cermin buat kita. Sudah sejauh mana perjuangan kita sendiri? 🤔",
  "Saya... jadi merasa kecil sekali sekarang, Prof. 😥",
  "Jangan merasa kecil. Ambil apinya, semangatnya. 🔥\nGunakan penamu ✍️, suaramu 🗣️, ilmumu 🧠 untuk menceritakan kisah mereka yg sebenarnya.\nItulah caramu ikut memanggul beban mereka.",
  "(Mengangguk mantap) Saya paham, Prof. Perjuangan mereka bukan cuma soal tanah.\nIni tentang menjaga marwah kemanusiaan dan keimanan. 🙏",
  "Tepat sekali. Mereka itu penjaga api. 🔥 Selama bara itu masih mereka genggam, harapan untuk umat ini akan selalu menyala.",
  "Terima kasih banyak, Prof. Anda memberi saya sudut pandang yg jauh lebih dalam. Ini bukan cerita tentang korban, tapi epik tentang kepahlawanan. ✨",
];

export default conversationCorpus;
